### ISSUE TITLE
please drop nodejs-legacy dependency

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [rospilot/rospilot#71]
Instead use `nodejs`, this is needed for compatibility with non-Debian distros

**Comment by cberner** [comment]
Does that work on Debian distros? Last I checked, `nodejs` didn't include the symlinks that `npm` needed on Debian

**Comment by Alessandro-Barbieri** [comment]
Do you *really* need these symlinks?
I just checked and `npm` depends on `nodejs`, not `nodejs-legacy`

**Comment by cberner** [comment]
It seems so. I tried removing that package and the npm portion of the build fails:
`/usr/bin/env: ‘node’: No such file or directory`. If you know how to make it work, please send a PR. I'd be happy to merge one!

**Comment by cberner** [comment]
Ah, actually I think I found a way to remove this. I'll try and take it out for the Lunar release I'm working on

**Comment by cberner** [comment]
https://github.com/rospilot/rospilot/commit/d1b72fe5ed2758b877eaadc864ca93c3667d73a4
